### ISSUE TITLE
public registration

### ISSUE THREAD

**Issue by simsasaile** [asipto/siremis-php#1]
Hi,

I set `$cfg_siremis_public_registrations` in `common.Main.php` to true as describe here: http://kb.asipto.com/siremis:install40x:public-registration
But unfortunately it's not working. If I try to open http://ydomain/siremis/user/register the normal login-window appears and if I log in and open the url of the registration form again, it shows up, but if I try to register a new user only the message: `Public registration is not enabled!` shows up.

Any suggestion?

**Comment by miconda** [comment]
Pushed a patch in master branch in order to try to fix it, but not time to test it. If the issue is still there, open a new one with the new details from using master branch.
