### ISSUE TITLE
Unable to login when using IPv6

### ISSUE THREAD

**Issue by imcdona** [asipto/siremis-php#15]
I'm unable to login to Siremis when using IPv6. The error is:

`Error in query:: INSERT INTO `event_log` (`user_id`, `ipaddr`, `event`, `message`, `comment`, `timestamp`) VALUES (:_v1, :_v2, :_v3, :_v4, :_v5, :_v6). SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ipaddr' at row 1`

The column ipaddr isn't long enough for IPv6 addresses and needs to be extended. I'm using the latest master.

**Comment by imcdona** [comment]
The following SQL will fix the issue:

`ALTER TABLE `event_log` CHANGE `ipaddr` `ipaddr` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;`

**Comment by imcdona** [comment]
I created pull request https://github.com/asipto/siremis/pull/17 with the required changes.

**Comment by miconda** [comment]
Fixed via PR #17.
