### ISSUE TITLE
Can't login after successful installation

### ISSUE THREAD

**Issue by davidcsi** [asipto/siremis-php#16]
Hello,

I've just installed siremis, all went well, no errors. Until i tried to login with the default admin/admin.

I got:

[{"target":"ERROR","content":"
\n[2017-05-17 09:41:28 (GMT)] An exception occurred while executing this script:
\nError message: #8192, Non-static method BizSystem::getConfiguration() should not be called statically, assuming $this from incompatible context<\/font>
\nScript name and line number of error: \/home\/www\/siremis\/openbiz\/bin\/data\/BizDataObj_Abstract.php:268<\/font>
\n

function:<\/b> errorHandler ( 8192, \"Non-static method BizSystem::getConfiguration() should not be ca...\", \"\/home\/www\/siremis\/openbiz\/bin\/data\/BizDataObj_Abstract.php\", 268, Array(0) ) @ \/home\/www\/siremis\/openbiz\/bin\/sysheader.inc 117\n
function:<\/b> userErrorHandler ( 8192, \"Non-static method BizSystem::getConfiguration() should not be ca...\", \"\/home\/www\/siremis\/openbiz\/bin\/data\/BizDataObj_Abstract.php\", 268, Array(0) ) @ \/home\/www\/siremis\/openbiz\/bin\/data\/BizDataObj_Abstract.php 268\n
function:<\/b> setQuoteIdentifiers ( ) @ \/home\/www\/siremis\/openbiz\/bin\/data\/BizDataObj_Abstract.php 177\n
function:<\/b> __construct ( Array(1) ) @ \/home\/www\/siremis\/openbiz\/bin\/data\/BizDataObj.php 37\n
function:<\/b> __construct ( Array(1) ) @ \/home\/www\/siremis\/openbiz\/bin\/ObjectFactory.php 166\n
function:<\/b> constructObject ( \"system.do.UserDO\" ) @ \/home\/www\/siremis\/openbiz\/bin\/ObjectFactory.php 56\n
function:<\/b> getObject ( \"system.do.UserDO\", 0 ) @ \/home\/www\/siremis\/openbiz\/bin\/BizSystem.php 252\n
function:<\/b> getObject ( \"system.do.UserDO\" ) @ \/home\/www\/siremis\/siremis\/modules\/service\/authService.php 92\n
function:<\/b> authDBUser ( \"admin\", \"admin\" ) @ \/home\/www\/siremis\/siremis\/modules\/service\/authService.php 66\n
function:<\/b> authenticateUser ( \"admin\", \"admin\" ) @ \/home\/www\/siremis\/siremis\/modules\/user\/form\/LoginForm.php 92\n
function:<\/b> Login ( ) @ \/home\/www\/siremis\/openbiz\/bin\/BizController.php 310\n
function:<\/b> invoke ( ) @ \/home\/www\/siremis\/openbiz\/bin\/BizController.php 110\n
function:<\/b> dispatchRequest ( ) @ \/home\/www\/siremis\/openbiz\/bin\/BizController.php 32\n
function:<\/b> include_once ( \"\/home\/www\/siremis\/openbiz\/bin\/BizController.php\" ) @ \/home\/www\/siremis\/siremis\/bin\/controller.php 6<\/div>\n
Please ask system administrator for help...<\/div>\n"}]

**Comment by miconda** [comment]
Did you use the git master version or the tarball?

**Comment by davidcsi** [comment]
Github Master

**Comment by miconda** [comment]
What OS and PHP version are you using?

**Comment by davidcsi** [comment]
Debian 8.6
PHP 5
ᐧ

Regards,

David Villasmil
email: david.villasmil.work@gmail.com
phone: +34669448337

**Comment by miconda** [comment]
Are you using exactly the version from git master? The line in the log message is not matching the code, see:

  * https://github.com/asipto/siremis/blob/master/openbiz/bin/data/BizDataObj_Abstract.php#L268

You just have to use what it is now in git master, no other external stuff.

**Comment by davidcsi** [comment]
I did git clone and used that one... i will delete it and restart again

**Comment by miconda** [comment]
I just did it using debian 8.8 and php 5. All works fine.

If you find anything, open a new issue, this one is not matching code anyhow.
