### ISSUE TITLE
duplicate key issue

### ISSUE THREAD

**Issue by dipenpatel235** [asipto/siremis-php#20]
hello...
i am using acc and cdr for accounting..
but getting duplicate issue so cdr is skip and due to that accounting is miss.

Below error when execute PROCEDURE `kamailio_cdrs`.

ERROR 1062 (23000) at line 1: Duplicate entry '2-rNf2C1Tc-ejTp~gJOf-U1g5rrSDD696r' for key 'uk_cft'

Thanks.

**Comment by miconda** [comment]
There seem to be two cdrs having same call-id, from-tag and to-tag. Can you check that in the acc table and see if there are many INVITE records with those values matching?

**Comment by dipenpatel235** [comment]
Yes.
I have seen that.
Many invite record entry are match.
That's why duplicate key issue.

So I am not understand it is unique then why it is generate duplicate many
invite ?

Thanks

**Comment by miconda** [comment]
The acc table doesn't have a constraint on the call, from-tag and to-tag. Based on your config for kamailio, the call can get more than one record for the same INVITE. If you do so, you need to adjust the stored procedures to deal with such cases.

The siremis cdr generation relies on the fact that kamailio writes a single INVTE record for each call in acc table.
