### ISSUE TITLE
cannot login, login page is displayed all time, even after a successuful authentication

### ISSUE THREAD

**Issue by defeden** [asipto/siremis-php#21]
I have followed the execution, i see that login is OK , then it call

 BizSystem::clientProxy()->ReDirectPage($redirectPage);

where redirectPage=/siremis/system/general_default

but the login page is displayed again and again

**Comment by miconda** [comment]
Can you look at the logs of your web server (e.g., apache) to see if there is anything printed there?

Just a double check list here:

  * be sure you enabled mod rewrite for apache
  * be sure you did chown for the folders (part of make prepare)
  * be sure you restarted web server

**Comment by defeden** [comment]
Hi;
I use centos 7, when i run this command:
1. httpd -M 
I see that mod rewrite is loaded

2. The folders is owned by apache user.


I have followed the execution of the php, I see that the function getUserProfile into openbiz/bin/BizSystem.php returns null (called by _forward.php), the function getUserProfile is called without any parameter into (_forward.php), so attribute variable is set by default to null. I think that a value of attribute should have a correct userid to log.

**Comment by defeden** [comment]
herein the dump of all vars before the first call to getUserProfile:

Array
(
      [_GET] => Array
      (
            [system/general_default] => 
      )
      [_POST] => Array
      (
      )
      [_COOKIE] => Array
      (
            [SYSTEM_SESSION_USERNAME] => admin
            [SYSTEM_SESSION_PASSWORD] => 0e06720d67be03a4e65b2891243ad83e
      )
      [_FILES] => Array
      (
      )
      [_SERVER] => Array
      (
            [REDIRECT_UNIQUE_ID] => Wb-NOlKmgzrrX30pM7ihSgAAAAA
            [REDIRECT_HTTP_MOD_REWRITE] => On
            [REDIRECT_STATUS] => 200
            [UNIQUE_ID] => Wb-NOlKmgzrrX30pM7ihSgAAAAA
            [HTTP_MOD_REWRITE] => On
            [HTTP_HOST] => 10.222.242.204:8087
            [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0
            [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
            [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.5
            [HTTP_ACCEPT_ENCODING] => gzip, deflate
            [HTTP_REFERER] => http://10.222.242.204:8087/siremis/index.php/user/login
            [HTTP_COOKIE] => SYSTEM_SESSION_USERNAME=admin; SYSTEM_SESSION_PASSWORD=0e06720d67be03a4e65b2891243ad83e
            [HTTP_CONNECTION] => keep-alive
            [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
            [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
            [SERVER_SIGNATURE] => 
            [SERVER_SOFTWARE] => Apache/2.4.6 (CentOS) PHP/5.4.16
            [SERVER_NAME] => 10.222.242.204
            [SERVER_ADDR] => 10.42.0.11
            [SERVER_PORT] => 8087
            [REMOTE_ADDR] => 10.222.241.110
            [DOCUMENT_ROOT] => /var/www/html
            [REQUEST_SCHEME] => http
            [CONTEXT_PREFIX] => 
            [CONTEXT_DOCUMENT_ROOT] => /var/www/html
            [SERVER_ADMIN] => root@localhost
            [SCRIPT_FILENAME] => /var/www/html/siremis/index.php
            [REMOTE_PORT] => 43770
            [REDIRECT_QUERY_STRING] => system/general_default
            [REDIRECT_URL] => /siremis/system/general_default
            [GATEWAY_INTERFACE] => CGI/1.1
            [SERVER_PROTOCOL] => HTTP/1.1
            [REQUEST_METHOD] => GET
            [QUERY_STRING] => system/general_default
            [REQUEST_URI] => /siremis/system/general_default
            [SCRIPT_NAME] => /siremis/index.php
            [PHP_SELF] => /siremis/index.php
            [REQUEST_TIME_FLOAT] => 1505742138.359
            [REQUEST_TIME] => 1505742138
     )
     [_REQUEST] => Array
     (
            [system/general_default] => 
     )
     [appHome] => /var/www/html/siremis
     [appPath] => /siremis
     [indexScript] => 
     [_SESSION] => Array
     (
            [LastAccessTime] => 1505742138
     )
     [g_BizSystem] => BizSystem Object
     (
            [_objectFactory:BizSystem:private] => 
            [_sessionContext:BizSystem:private] => SessionContext Object
            (
                    [_lastAccessTime:protected] => 1505742138
                    [_timeOut:protected] => 
                    [_sessObjArr:protected] => Array
                    (
                    )
                    [_statefulSessObjArr:protected] => Array
                    (
                    )
                    [_sessObjFileName:protected] => /var/www/html/siremis/session/ri2m1td2ovve2hl0nfj2qds8k2_obj
                    [_viewHistory:protected] => 
                    [_prevViewObjNames:protected] => Array
                    (                        
		    )
            )
            [_confgiuration:BizSystem:private] => 
            [_clientProxy:BizSystem:private] => 
            [_typeManager:BizSystem:private] => 
            [_currentViewName:BizSystem:private] => 
            [_currentViewSet:BizSystem:private] => 
            [_dbConnection:BizSystem:private] => Array
            (
            )
            [_theme:BizSystem:private] => Array
            (
            )
            [_serviceList:BizSystem:private] => Array
            (
            )
            [_userProfile:BizSystem:private] => 
     )
     [default_error_handler] => 
     [default_exception_handler] => 
     [DEFAULT_VIEW] => LoginView
     [DEFAULT_MODULE] => user
     [DEFAULT_URL] => index.php/user/login
     [url] => system/general_default
     [match] => Array
     (
          [0] => system/general_default
          [1] => system/general_default
     )
     [urlArr] => Array
     (
     )
)

**Comment by defeden** [comment]
I have resolved the issue, it was related to my firefox web browser, i have refreshed it, and can log now
