### ISSUE TITLE
Error 500 fresh install

### ISSUE THREAD

**Issue by noobchamp** [asipto/siremis-php#25]
PHP Fatal error:  require_once(): Failed opening required 'SMARTY_CORE_DIRcore.assemble_plugin_filepath.php' (include_path='.:/usr/share/pear:/usr/share/php:/var/www/html/siremis/openbiz/others/') in /var/www/html/siremis/openbiz/others/Smarty/libs/Smarty.class.php on line 1368

Can you help me?

Thanks

**Comment by miconda** [comment]
Can you list here the commands and steps you did to install?

What is the operating system, web server and php version?

On a Debian 9 with php7 all goes smooth.

**Comment by miconda** [comment]
With no follow up, I am going to close it. Re-open if you have updates.
