### ISSUE TITLE
XMLRPC Commands output

### ISSUE THREAD

**Issue by atpw-voip** [asipto/siremis-php#28]
Fresh install Kamailio 5.1.4, Debian Stretch, Apache 2.4.25, php 7.0.27

I am testing your past version and in IE, Firefox and Safari I have obtained the following output from Server - Uptime command:

\<methodResponse>
\<params>
\<param>
\<value>\<struct>
\<member>\<name>now\</name>
\<value>\<string>Fri Jul  6 22:24:47 2018\</string>\</value>
\</member>
\<member>\<name>up_since\</name>
\<value>\<string>Fri Jul  6 21:52:24 2018\</string>\</value>
\</member>
\<member>\<name>uptime\</name>
\<value>\<int>1943\</int>\</value>
\</member>
\</struct></value>
\</param>
\</params>
\</methodResponse>

Another commands have a similar output.

**Comment by miconda** [comment]
What is the actual problem you want to report?

**Comment by atpw-voip** [comment]
Except system.listMethods command output there are the XMLRPC tags displayed in outputs of all other commands.

**Comment by miconda** [comment]
That page offers a raw xmlrpc client, it doesn't try to interpret the result of xmlrpc commands.

If you want something different, then you will have to write some php code. We can consider merging the code if you make a pull request and all is ok.
