### ISSUE TITLE
JSONRPC Command System Internal Error and infinite page loading

### ISSUE THREAD

**Issue by atpw-voip** [asipto/siremis-php#29]
All JSONRPC Commands end is System Internal Error and infinite page loading with the following lines in apache error.log:

PHP Warning:  strstr() expects parameter 1 to be string, resource given in /var/www/siremis-5.1.0/openbiz/bin/ErrorHandler.php on line 154, referer: http://192.168.1.150/siremis/sipadmin/jrcmds

socket bind failed: No such file or directory, referer: http://192.168.1.150/siremis/sipadmin/jrcmds

**Comment by miconda** [comment]
Kamailio or Siremis are not configured properly to communicate via socket, see the xml config for hints:

  * https://github.com/asipto/siremis/blob/073a9223e2abb9a3ba911083c02509fcc0215df1/siremis/modules/sipadmin/service/siremisJRCommands.xml#L3-L14
