### ISSUE TITLE
New Siremis user can't log in

### ISSUE THREAD

**Issue by k4r7u** [asipto/siremis-php#3]
After adding a new user through Siremis User Management, this user isn't able to log in.
The log in interface just stays at "Processing Login".
Also clicking on a Serims username gives a blank page.

**Comment by bdwkyy** [comment]
i have the same problem.could you give me a help?

**Comment by henkpls** [comment]
You probably have no database created in web installation wizard step 2:

--> When you install Siremis first time, you probably have to check:
    Create Siremis Database - this create database 'siremis'
    Import Default Data - this imports initial data into database 'siremis'
    Update SIP Database - this updates the structure of Kamailio database for accounting and charts modules
    Replace DB Config - this updates Siremis configuration file with the details to access databases

So to redo the installation remove file: siremis/install.lock en restart.

**Comment by keffa2015** [comment]
same issu for me:
`[{"target":"ERROR","content":"
\n[2016-05-19 22:33:52 (GMT)] An exception occurred while executing this script:
\nError message: #8192, Non-static method BizSystem::getConfiguration() should not be called statically, assuming $this from incompatible context<\/font>
\nScript name and line number of error: \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php:268<\/font>
\n

function:<\/b> errorHandler ( 8192, \"Non-static method BizSystem::getConfiguration() should not be ca...\", \"\/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php\", 268, Array(0) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/sysheader.inc 117\n
function:<\/b> userErrorHandler ( 8192, \"Non-static method BizSystem::getConfiguration() should not be ca...\", \"\/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php\", 268, Array(0) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php 268\n
function:<\/b> setQuoteIdentifiers ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php 177\n
function:<\/b> __construct ( Array(1) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj.php 37\n
function:<\/b> __construct ( Array(1) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/ObjectFactory.php 166\n
function:<\/b> constructObject ( \"system.do.UserDO\" ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/ObjectFactory.php 56\n
function:<\/b> getObject ( \"system.do.UserDO\", 0 ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizSystem.php 252\n
function:<\/b> getObject ( \"system.do.UserDO\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/modules\/service\/authService.php 92\n
function:<\/b> authDBUser ( \"admin\", \"admin\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/modules\/service\/authService.php 66\n
function:<\/b> authenticateUser ( \"admin\", \"admin\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/modules\/user\/form\/LoginForm.php 92\n
function:<\/b> Login ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php 310\n
function:<\/b> invoke ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php 110\n
function:<\/b> dispatchRequest ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php 32\n
function:<\/b> include_once ( \"\/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/bin\/controller.php 6<\/div>\n
Please ask system administrator for help...<\/div>\n"}]`

**Comment by keffa2015** [comment]
Use source from here (git: https://github.com/asipto/siremis.git).
Avoid http://siremis.asipto.com/pub/downloads/siremis/siremis-4.2.0.tgz, it is not updated

**Comment by miconda** [comment]
Try latest master, there were some fixes recently.
