### ISSUE TITLE
Unable to login after install on Ubuntu 18.04

### ISSUE THREAD

**Issue by ehosch** [asipto/siremis-php#30]
Fresh Install
Kamailio v5.1
Siremis from master branch https://github.com/asipto/siremis.git
PHP v7.2
php-mysql php-gd php-curl php-xml php-xmlrpc php-json libapache2-mod-php php-pear

No errors in Kamailio log but

Error message web popup says -

'

    [{"target":"ERROR","content":"
	\n[2018-07-17 16:35:34 (GMT)] An exception occurred while executing this script:
	\nError message: #2, Use of undefined constant META_PATH - assumed 'META_PATH' (this will throw an Error in a future version of PHP)<\/font>
	\nScript name and line number of error: \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/Resource.php:242<\/font>
	\n

	function:<\/b> errorHandler ( 2, \"Use of undefined constant META_PATH - assumed 'META_PATH' (this ...\", \"\/var\/www\/kamailio-5.1.0\/openbiz\/bin\/Resource.php\", 242, Array(2) ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/sysheader.inc 117\n
	function:<\/b> userErrorHandler ( 2, \"Use of undefined constant META_PATH - assumed 'META_PATH' (this ...\", \"\/var\/www\/kamailio-5.1.0\/openbiz\/bin\/Resource.php\", 242, Array(2) ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/Resource.php 242\n
	function:<\/b> getXmlFileWithPath ( \"service.logService\" ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/BizSystem.php 549\n
	function:<\/b> getXmlFileWithPath ( \"service.logService\" ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/ObjectFactory.php 104\n
	function:<\/b> constructObject ( \"service.logService\" ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/ObjectFactory.php 56\n
	function:<\/b> getObject ( \"service.logService\", 0 ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/BizSystem.php 252\n
	function:<\/b> getObject ( \"service.logService\", 0 ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/BizSystem.php 241\n
	function:<\/b> getService ( \"service.logService\" ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/BizSystem.php 507\n
	function:<\/b> log ( 7, \"DATAOBJ\", \"Query Sql = SELECT T0.id, T0.username, T0.password, T0.enctype, ...\" ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/data\/BizDataObj_Lite.php 438\n
	function:<\/b> _run_search ( Array(2) ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/data\/BizDataObj_Lite.php 345\n
	function:<\/b> fetchRecords ( \"[username]='admin' and status='1'\", Array(0), 1 ) @ \/var\/www\/kamailio-5.1.0\/siremis\/modules\/service\/authService.php 98\n
	function:<\/b> authDBUser ( \"admin\", \"admin\" ) @ \/var\/www\/kamailio-5.1.0\/siremis\/modules\/service\/authService.php 66\n
	function:<\/b> authenticateUser ( \"admin\", \"admin\" ) @ \/var\/www\/kamailio-5.1.0\/siremis\/modules\/user\/form\/LoginForm.php 93\n
	function:<\/b> Login ( ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/BizController.php 310\n
	function:<\/b> invoke ( ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/BizController.php 110\n
	function:<\/b> dispatchRequest ( ) @ \/var\/www\/kamailio-5.1.0\/openbiz\/bin\/BizController.php 32\n
	function:<\/b> include_once ( \"\/var\/www\/kamailio-5.1.0\/openbiz\/bin\/BizController.php\" ) @ \/var\/www\/kamailio-5.1.0\/siremis\/bin\/controller.php 6<\/div>\n
	Please ask system administrator for help...<\/div>\n"}]

'

**Comment by miconda** [comment]
Should be fixed by the commit referenced above. Try with latest master branch and if still an issue, reopen and add logs printed with latest version.

**Comment by ehosch** [comment]
Thanks, for quick fix...now new error:


	[2018-07-17 18:13:53 (GMT)] An exception occurred while executing this script:
	Error message: #8192, The each() function is deprecated. This message will be suppressed on further calls
	Script name and line number of error: /var/www/kamailio-5.1.0/openbiz/others/Zend/Cache/Backend.php:66

	function: errorHandler ( 8192, "The each() function is deprecated. This message will be suppress...", "/var/www/kamailio-5.1.0/openbiz/others/Zend/Cache/Backend.php", 66, Array(1) ) @ /var/www/kamailio-5.1.0/openbiz/bin/sysheader.inc 117 
	function: userErrorHandler ( 8192, "The each() function is deprecated. This message will be suppress...", "/var/www/kamailio-5.1.0/openbiz/others/Zend/Cache/Backend.php", 66, Array(1) ) @ 
	function: each ( Array(7) ) @ /var/www/kamailio-5.1.0/openbiz/others/Zend/Cache/Backend.php 66 
	function: __construct ( Array(7) ) @ /var/www/kamailio-5.1.0/openbiz/others/Zend/Cache/Backend/File.php 119 
	function: __construct ( Array(7) ) @ /var/www/kamailio-5.1.0/openbiz/others/Zend/Cache.php 152 
	function: _makeBackend ( "File", Array(7), False, False ) @ /var/www/kamailio-5.1.0/openbiz/others/Zend/Cache.php 93 
	function: factory ( "Core", "File", Array(4), Array(7) ) @ /var/www/kamailio-5.1.0/openbiz/bin/service/cacheService.php 166 
	function: init ( "menu.do.MenuTreeDO", "7200" ) @ /var/www/kamailio-5.1.0/openbiz/bin/data/BizDataObj_Lite.php 422 
	function: _run_search ( Null ) @ /var/www/kamailio-5.1.0/openbiz/bin/data/BizDataObj_Lite.php 281 
	function: directFetch ( "[PId]='System' AND [published] = 1" ) @ /var/www/kamailio-5.1.0/siremis/modules/menu/do/MenuTreeDO.php 59 
	function: fetchTreeBySearchRule ( "[PId]='System'", "2", "[published] = 1" ) @ /var/www/kamailio-5.1.0/siremis/modules/menu/widget/MenuWidget.php 79 
	function: fetchMenuTree ( ) @ /var/www/kamailio-5.1.0/siremis/modules/menu/widget/MenuWidget.php 93 
	function: outputAttrs ( ) @ /var/www/kamailio-5.1.0/siremis/modules/menu/widget/MenuRenderer.php 54 
	function: renderSmarty ( Object(MenuWidget), "/var/www/kamailio-5.1.0/siremis/modules/menu/template/sitemap_me..." ) @ /var/www/kamailio-5.1.0/siremis/modules/menu/widget/MenuRenderer.php 39 
	function: render ( Object(MenuWidget) ) @ /var/www/kamailio-5.1.0/siremis/modules/menu/widget/MenuWidget.php 72 
	function: renderHTML ( ) @ /var/www/kamailio-5.1.0/siremis/modules/menu/widget/MenuWidget.php 65 
	function: render ( ) @ /var/www/kamailio-5.1.0/openbiz/bin/easy/ViewRenderer.php 83 
	function: renderSmarty ( Object(EasyView), "/var/www/kamailio-5.1.0/siremis/themes/default/template/system_v..." ) @ /var/www/kamailio-5.1.0/openbiz/bin/easy/ViewRenderer.php 40 
	function: render ( Object(EasyView) ) @ /var/www/kamailio-5.1.0/openbiz/bin/easy/EasyView.php 274 
	function: _render ( ) @ /var/www/kamailio-5.1.0/openbiz/bin/easy/EasyView.php 237 
	function: render ( ) @ /var/www/kamailio-5.1.0/openbiz/bin/BizController.php 221 
	function: renderView ( "system.view.GeneralDefaultView", "", "", Null, "" ) @ /var/www/kamailio-5.1.0/openbiz/bin/BizController.php 107 
	function: dispatchRequest ( ) @ /var/www/kamailio-5.1.0/openbiz/bin/BizController.php 32 
	function: include_once ( "/var/www/kamailio-5.1.0/openbiz/bin/BizController.php" ) @ /var/www/kamailio-5.1.0/siremis/bin/controller.php 6 
	function: include ( "/var/www/kamailio-5.1.0/siremis/bin/controller.php" ) @ /var/www/kamailio-5.1.0/siremis/bin/_forward.php 102 
	function: include ( "/var/www/kamailio-5.1.0/siremis/bin/_forward.php" ) @ /var/www/kamailio-5.1.0/siremis/index.php 3

**Comment by farmorg** [comment]
Hi, also having login issues using Git Master on Ubuntu Server 18.04.1, PHP 7.2

`[{"target":"ERROR","content":"
\n[2018-08-22 10:28:52 (GMT)] An exception occurred while executing this script:
\nError message: #2, Use of undefined constant META_PATH - assumed 'META_PATH' (this will throw an Error in a future version of PHP)<\/font>
\nScript name and line number of error: \/usr\/local\/src\/siremis\/openbiz\/bin\/Resource.php:242<\/font>
\n

function:<\/b> errorHandler ( 2, \"Use of undefined constant META_PATH - assumed 'META_PATH' (this ...\", \"\/usr\/local\/src\/siremis\/openbiz\/bin\/Resource.php\", 242, Array(2) ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/sysheader.inc 117\n
function:<\/b> userErrorHandler ( 2, \"Use of undefined constant META_PATH - assumed 'META_PATH' (this ...\", \"\/usr\/local\/src\/siremis\/openbiz\/bin\/Resource.php\", 242, Array(2) ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/Resource.php 242\n
function:<\/b> getXmlFileWithPath ( \"service.logService\" ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/BizSystem.php 549\n
function:<\/b> getXmlFileWithPath ( \"service.logService\" ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/ObjectFactory.php 104\n
function:<\/b> constructObject ( \"service.logService\" ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/ObjectFactory.php 56\n
function:<\/b> getObject ( \"service.logService\", 0 ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/BizSystem.php 252\n
function:<\/b> getObject ( \"service.logService\", 0 ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/BizSystem.php 241\n
function:<\/b> getService ( \"service.logService\" ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/BizSystem.php 507\n
function:<\/b> log ( 7, \"DATAOBJ\", \"Query Sql = SELECT T0.id, T0.username, T0.password, T0.enctype, ...\" ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/data\/BizDataObj_Lite.php 438\n
function:<\/b> _run_search ( Array(2) ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/data\/BizDataObj_Lite.php 345\n
function:<\/b> fetchRecords ( \"[username]='admin' and status='1'\", Array(0), 1 ) @ \/usr\/local\/src\/siremis\/siremis\/modules\/service\/authService.php 98\n
function:<\/b> authDBUser ( \"admin\", \"admin\" ) @ \/usr\/local\/src\/siremis\/siremis\/modules\/service\/authService.php 66\n
function:<\/b> authenticateUser ( \"admin\", \"admin\" ) @ \/usr\/local\/src\/siremis\/siremis\/modules\/user\/form\/LoginForm.php 93\n
function:<\/b> Login ( ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/BizController.php 310\n
function:<\/b> invoke ( ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/BizController.php 110\n
function:<\/b> dispatchRequest ( ) @ \/usr\/local\/src\/siremis\/openbiz\/bin\/BizController.php 32\n
function:<\/b> include_once ( \"\/usr\/local\/src\/siremis\/openbiz\/bin\/BizController.php\" ) @ \/usr\/local\/src\/siremis\/siremis\/bin\/controller.php 6<\/div>\nPlease ask system administrator for help...<\/div>\n"}]
`
