### ISSUE TITLE
can't open cmp file to write

### ISSUE THREAD

**Issue by JayTheLegend** [asipto/siremis-php#32]
After a clean install of 5.1 seems to be some access issues of the cmp file. During the web config I used to get this error, but after giving the www-data user access to siremis file the installation went down with no problem. However I cant get to the login screen right after the install, "can't open cmp file to write". Where is this file and what user is accessing this?

**Comment by miconda** [comment]
Have you done `make prepare` and `make chown`?

**Comment by JayTheLegend** [comment]
You are correct, however I am having difficulties doing so. I am following this tutorial: http://kb.asipto.com/siremis:install51x:main and can't seem to find the files. I downloaded from Github and the file structure does not seem to match the tutorial. I.E Siremis directory is inside the Kamailio one with no version as suggested by the tutorial. I would try the tarball, but only 4.4.0 is available.

root@SipTest:/var/www/kamailio-5.1.0# dir
ChangeLog  Makefile  misc  openbiz  README.md  siremis

root@SipTest:/var/www/kamailio-5.1.0/siremis# dir
bin	    favicon.ico  index.php     js	  modules  themes
build	    files	 install       languages  pages
Config.xml  images	 install.lock  log	  session

**Comment by JayTheLegend** [comment]
So I when't back a directory and run make prepare24 and it worked. The Tutorial is a little ambiguous around where the command should be run. in my case it was /var/www/kamailio-5.1.0/ afterwards I deleted the databases, install.lock and rerun the web install.
