### ISSUE TITLE
SIP User Menu errors PHP 7.2, MariaDB 10.3.9, Apache 2.4.34

### ISSUE THREAD

**Issue by lewo** [asipto/siremis-php#34]
Hi, I'm getting the following error on the master branch when trying to access SIP User Menu/Location Records (or any of the other items).

[2018-10-31 05:42:05 (GMT)] An exception occurred while executing this script:
Error message: #2, Use of undefined constant admin - assumed 'admin' (this will throw an Error in a future version of PHP)
Script name and line number of error: /var/www/html/siremis/openbiz/bin/Expression.php(329) : eval()'d code:1

function: errorHandler ( 2, "Use of undefined constant admin - assumed 'admin' (this will thr...", "/var/www/html/siremis/openbiz/bin/Expression.php(329) : eval()'d...", 1, Array(7) ) @ /var/www/html/siremis/openbiz/bin/sysheader.inc 117 
function: userErrorHandler ( 2, "Use of undefined constant admin - assumed 'admin' (this will thr...", "/var/www/html/siremis/openbiz/bin/Expression.php(329) : eval()'d...", 1, Array(7) ) @ /var/www/html/siremis/openbiz/bin/Expression.php(329) : eval()'d code 1 
function: eval ( ) @ /var/www/html/siremis/openbiz/bin/Expression.php 329 
function: evaluateExpression ( "'[username]'=='{@profile:username}'", Object(SubscriberDO) ) @ /var/www/html/siremis/openbiz/bin/data/private/BizDataObj_SQLHelper.php 318 
function: _ruleToSql ( Object(SubscriberDO), "'[username]'=='{@profile:username}'" ) @ /var/www/html/siremis/openbiz/bin/data/private/BizDataObj_SQLHelper.php 124 
function: buildQuerySQL ( Object(SubscriberDO) ) @ /var/www/html/siremis/openbiz/bin/data/BizDataObj_Lite.php 403 
function: _run_search ( Array(2) ) @ /var/www/html/siremis/openbiz/bin/data/BizDataObj_Lite.php 243 
function: fetch ( ) @ /var/www/html/siremis/openbiz/bin/easy/EasyForm.php 690 
function: fetchDataSet ( ) @ /var/www/html/siremis/openbiz/bin/easy/FormRenderer.php 69 
function: renderSmarty ( Object(EasyForm), "/var/www/html/siremis/siremis/modules/sipuser/template/grid.tpl" ) @ /var/www/html/siremis/openbiz/bin/easy/FormRenderer.php 45 
function: render ( Object(EasyForm) ) @ /var/www/html/siremis/openbiz/bin/easy/EasyForm.php 1648 
function: renderHTML ( ) @ /var/www/html/siremis/openbiz/bin/easy/EasyForm.php 1538 
function: render ( ) @ /var/www/html/siremis/openbiz/bin/easy/ViewRenderer.php 83 
function: renderSmarty ( Object(EasyView), "/var/www/html/siremis/siremis/modules/sipuser/template/view_tabs..." ) @ /var/www/html/siremis/openbiz/bin/easy/ViewRenderer.php 40 
function: render ( Object(EasyView) ) @ /var/www/html/siremis/openbiz/bin/easy/EasyView.php 274 
function: _render ( ) @ /var/www/html/siremis/openbiz/bin/easy/EasyView.php 237 
function: render ( ) @ /var/www/html/siremis/openbiz/bin/BizController.php 221 
function: renderView ( "sipuser.view.SubscriberListView", "", "", Null, "" ) @ /var/www/html/siremis/openbiz/bin/BizController.php 107 
function: dispatchRequest ( ) @ /var/www/html/siremis/openbiz/bin/BizController.php 32 
function: include_once ( "/var/www/html/siremis/openbiz/bin/BizController.php" ) @ /var/www/html/siremis/siremis/bin/controller.php 6 
function: include ( "/var/www/html/siremis/siremis/bin/controller.php" ) @ /var/www/html/siremis/siremis/bin/_forward.php 102 
function: include ( "/var/www/html/siremis/siremis/bin/_forward.php" ) @ /var/www/html/siremis/siremis/index.php 3

**Comment by miconda** [comment]
Can you test again with latest master? I just pushed several commits for it and all seems to go fine on Debian Testing with PHP 7.2. If still an issue, reopen. Thanks!

**Comment by lewo** [comment]
Will do
