### ISSUE TITLE
siremis makefile hard path, able to customize for packagin

### ISSUE THREAD

**Issue by mckaygerhard** [asipto/siremis-php#37]
in makefile there that line:

`BASEDIR=`pwd` `

must be changed to 

`BASEDIR ?= `pwd` `

to property able to use the makefile for customized instalations, same for `VERSION` to hable to make sub-releases per distributions.. so we support this are not installable in windo like poor OS's

**Comment by miconda** [comment]
Pushed the commit referenced above.
