### ISSUE TITLE
Wrong timezone

### ISSUE THREAD

**Issue by k4r7u** [asipto/siremis-php#4]
Siremis seems to calculate times based on a wrong timezone.
In "ACC charts" I can see "Timezone: America/Los_Angeles".
Kamailio on the other hand uses the right timezone.

Is there a way to change the timezone in Siremis?

**Comment by virmis** [comment]
I've changed mine here and it works for me:
siremis-4.2.0/siremis/bin/app.inc
date_default_timezone_set('Europe/Vilnius');

**Comment by miconda** [comment]
The latest master should not enforce a timezone anymore. If not working, reopen.
