### ISSUE TITLE
Last modified dates in the forms is 1900-01-01 00:00:01  by default

### ISSUE THREAD

**Issue by xevilstar** [asipto/siremis-php#44]
hello, I think that last modified date should correspond at the time when the change occurs and not somewhere in the 1900......

**Comment by xevilstar** [comment]
$timezone = date_default_timezone_get();
and then workout the default from there ?

**Comment by xevilstar** [comment]
grep date /etc/php/7.3/apache2/php.ini 
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone = Europe/Rome

grep date /etc/php/7.3/cli/php.ini 
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone = Europe/Rome
date
Fri May 31 11:09:02 CEST 2019

**Comment by miconda** [comment]
The last modified date is actually not used, it was added to kamailio table in the early phase of development when the project was named SER and there was serweb using this column.

Right now you can select the today's value with the date pick calendar button next to the input field.

If you want it to be automatically current date, then make a pull request and it will be merged if all ok.

**Comment by xevilstar** [comment]
I am not a developer I just test and report. 
by the way.... where are all my reports about links crashing ?

**Comment by miconda** [comment]
Then I will close it and leave it as it is with the option to set last modified value by input field or selecting from the calendar window. Again, if someone wants to adjust this behavior, just make a pull request.
