### ISSUE TITLE
cannot add languages

### ISSUE THREAD

**Issue by xevilstar** [asipto/siremis-php#45]
[2019-05-31 09:16:55 (GMT)] An exception occurred while executing this script:
Error message: #2, Declaration of RegionListbox::getFromList(&$list) should be compatible with OptionElement::getFromList(&$list, $selectFrom = NULL)
Script name and line number of error: /var/www/html/siremis/siremis/modules/translation/form/RegionListbox.php:3

function: errorHandler ( 2, "Declaration of RegionListbox::getFromList(&$list) should be comp...", "/var/www/html/siremis/siremis/modules/translation/form/RegionLis...", 3, Array(6) ) @ /var/www/html/siremis/openbiz/bin/sysheader.inc 117
function: userErrorHandler ( 2, "Declaration of RegionListbox::getFromList(&$list) should be comp...", "/var/www/html/siremis/siremis/modules/translation/form/RegionLis...", 3, Array(6) ) @ /var/www/html/siremis/siremis/modules/translation/form/RegionListbox.php 3
function: require_once ( "/var/www/html/siremis/siremis/modules/translation/form/RegionLis..." ) @ /var/www/html/siremis/openbiz/bin/sysclass.inc 220
function: __construct ( Array(10), "", Object(LanguageForm) ) @ /var/www/html/siremis/openbiz/bin/easy/Panel.php 32
function: __construct ( Array(10), "", Object(LanguageForm) ) @ /var/www/html/siremis/openbiz/bin/easy/EasyForm.php 154
function: readMetadata ( Array(1) ) @ /var/www/html/siremis/openbiz/bin/easy/EasyForm.php 120
function: __construct ( Array(1) ) @ /var/www/html/siremis/openbiz/bin/ObjectFactory.php 166
function: constructObject ( "translation.form.LanguageNewForm" ) @ /var/www/html/siremis/openbiz/bin/ObjectFactory.php 56
function: getObject ( "translation.form.LanguageNewForm" ) @ /var/www/html/siremis/openbiz/bin/easy/EasyForm.php 938
function: _showForm ( "translation.form.LanguageNewForm", Null, Array(0) ) @ /var/www/html/siremis/openbiz/bin/easy/EasyForm.php 1747
function: switchForm ( "translation.form.LanguageNewForm" ) @ /var/www/html/siremis/openbiz/bin/BizController.php 311
function: invoke ( ) @ /var/www/html/siremis/openbiz/bin/BizController.php 110
function: dispatchRequest ( ) @ /var/www/html/siremis/openbiz/bin/BizController.php 32
function: include_once ( "/var/www/html/siremis/openbiz/bin/BizController.php" ) @ /var/www/html/siremis/siremis/bin/controller.php 6

**Comment by miconda** [comment]
Should be fixed by latest commits in master branch, reopen if still an issue.
