### ISSUE TITLE
siremis/menu/menu_list crashes

### ISSUE THREAD

**Issue by xevilstar** [asipto/siremis-php#46]
[2019-05-31 09:18:50 (GMT)] An exception occurred while executing this script:
Error message: #2, A non-numeric value encountered
Script name and line number of error: /var/www/html/siremis/openbiz/bin/Expression.php(336) : eval()'d code:1

function: errorHandler ( 2, "A non-numeric value encountered", "/var/www/html/siremis/openbiz/bin/Expression.php(336) : eval()'d...", 1, Array(7) ) @ /var/www/html/siremis/openbiz/bin/sysheader.inc 117
function: userErrorHandler ( 2, "A non-numeric value encountered", "/var/www/html/siremis/openbiz/bin/Expression.php(336) : eval()'d...", 1, Array(7) ) @ /var/www/html/siremis/openbiz/bin/Expression.php(336) : eval()'d code 1
function: eval ( ) @ /var/www/html/siremis/openbiz/bin/Expression.php 336
function: evaluateExpression ( "menu.form.MenuListForm.UpdateFieldValue({@:Elem[fld_Id].Value},f...", Object(MenuForm) ) @ /var/www/html/siremis/openbiz/bin/easy/element/Element.php 637
function: getFormedFunction ( ) @ /var/www/html/siremis/openbiz/bin/easy/element/ColumnSorting.php 90
function: getBtnFunction ( "fld_sortorder_up" ) @ /var/www/html/siremis/openbiz/bin/easy/element/ColumnSorting.php 7
function: render ( ) @ /var/www/html/siremis/openbiz/bin/easy/Panel.php 54
function: render ( ) @ /var/www/html/siremis/openbiz/bin/easy/Panel.php 94
function: renderTable ( Array(3) ) @ /var/www/html/siremis/openbiz/bin/easy/FormRenderer.php 70
function: renderSmarty ( Object(MenuForm), "/var/www/html/siremis/siremis/themes/default/template/system_rig..." ) @ /var/www/html/siremis/openbiz/bin/easy/FormRenderer.php 45
function: render ( Object(MenuForm) ) @ /var/www/html/siremis/openbiz/bin/easy/EasyForm.php 1648
function: renderHTML ( ) @ /var/www/html/siremis/openbiz/bin/easy/EasyForm.php 1538
function: render ( ) @ /var/www/html/siremis/siremis/modules/menu/form/MenuForm.php 48
function: render ( ) @ /var/www/html/siremis/openbiz/bin/easy/ViewRenderer.php 83
function: renderSmarty ( Object(EasyView), "/var/www/html/siremis/siremis/modules/menu/template/view.tpl" ) @ /var/www/html/siremis/openbiz/bin/easy/ViewRenderer.php 40
function: render ( Object(EasyView) ) @ /var/www/html/siremis/openbiz/bin/easy/EasyView.php 274
function: _render ( ) @ /var/www/html/siremis/openbiz/bin/easy/EasyView.php 237
function: render ( ) @ /var/www/html/siremis/openbiz/bin/BizController.php 221
function: renderView ( "menu.view.MenuListView", "", "", Null, "" ) @ /var/www/html/siremis/openbiz/bin/BizController.php 107
function: dispatchRequest ( ) @ /var/www/html/siremis/openbiz/bin/BizController.php 32
function: include_once ( "/var/www/html/siremis/openbiz/bin/BizController.php" ) @ /var/www/html/siremis/siremis/bin/controller.php 6
function: include ( "/var/www/html/siremis/siremis/bin/controller.php" ) @ /var/www/html/siremis/siremis/bin/_forward.php 102
function: include ( "/var/www/html/siremis/siremis/bin/_forward.php" ) @ /var/www/html/siremis/siremis/index.php 3

**Comment by miconda** [comment]
Should be fixed by latest commits in master branch, reopen if still an issue.
