### ISSUE TITLE
siremis/cache/manage crashes

### ISSUE THREAD

**Issue by xevilstar** [asipto/siremis-php#48]
[2019-05-31 09:21:23 (GMT)] An exception occurred while executing this script:
Error message: #2, A non-numeric value encountered
Script name and line number of error: /var/www/html/siremis/openbiz/bin/easy/element/ColumnBar.php:35

function: errorHandler ( 2, "A non-numeric value encountered", "/var/www/html/siremis/openbiz/bin/easy/element/ColumnBar.php", 35, Array(7) ) @ /var/www/html/siremis/openbiz/bin/sysheader.inc 117
function: userErrorHandler ( 2, "A non-numeric value encountered", "/var/www/html/siremis/openbiz/bin/easy/element/ColumnBar.php", 35, Array(7) ) @ /var/www/html/siremis/openbiz/bin/easy/element/ColumnBar.php 35
function: render ( ) @ /var/www/html/siremis/openbiz/bin/easy/Panel.php 54
function: render ( ) @ /var/www/html/siremis/openbiz/bin/easy/Panel.php 94
function: renderTable ( Null ) @ /var/www/html/siremis/openbiz/bin/easy/FormRenderer.php 70
function: renderSmarty ( Object(CacheForm), "/var/www/html/siremis/siremis/modules/cache/template/grouping.tp..." ) @ /var/www/html/siremis/openbiz/bin/easy/FormRenderer.php 45
function: render ( Object(CacheForm) ) @ /var/www/html/siremis/openbiz/bin/easy/EasyForm.php 1648
function: renderHTML ( ) @ /var/www/html/siremis/openbiz/bin/easy/EasyForm.php 1538
function: render ( ) @ /var/www/html/siremis/openbiz/bin/easy/ViewRenderer.php 83
function: renderSmarty ( Object(EasyView), "/var/www/html/siremis/siremis/modules/cache/template/view.tpl" ) @ /var/www/html/siremis/openbiz/bin/easy/ViewRenderer.php 40
function: render ( Object(EasyView) ) @ /var/www/html/siremis/openbiz/bin/easy/EasyView.php 274
function: _render ( ) @ /var/www/html/siremis/openbiz/bin/easy/EasyView.php 237
function: render ( ) @ /var/www/html/siremis/openbiz/bin/BizController.php 221
function: renderView ( "cache.view.ManageView", "", "", Null, "" ) @ /var/www/html/siremis/openbiz/bin/BizController.php 107
function: dispatchRequest ( ) @ /var/www/html/siremis/openbiz/bin/BizController.php 32
function: include_once ( "/var/www/html/siremis/openbiz/bin/BizController.php" ) @ /var/www/html/siremis/siremis/bin/controller.php 6
function: include ( "/var/www/html/siremis/siremis/bin/controller.php" ) @ /var/www/html/siremis/siremis/bin/_forward.php 102
function: include ( "/var/www/html/siremis/siremis/bin/_forward.php" ) @ /var/www/html/siremis/siremis/index.php 3
Please ask system administrator for help...

Report to admin
Show Error

**Comment by miconda** [comment]
Should be fixed by latest commits in master branch, reopen if still an issue.
