### ISSUE TITLE
just did a git pull origin master and http://10.5.0.1/siremis/sipadmin/xrcmds now crashes

### ISSUE THREAD

**Issue by xevilstar** [asipto/siremis-php#50]
2019-05-31 14:25:25 (GMT)] An exception occurred while executing this script:
Error message: #2, require_once(XML/RPC.php): failed to open stream: No such file or directory
Script name and line number of error: /var/www/html/siremis/siremis/modules/sipadmin/service/asipto/libs/cmds/serxr.php:2

function: errorHandler ( 2, "require_once(XML/RPC.php): failed to open stream: No such file o...", "/var/www/html/siremis/siremis/modules/sipadmin/service/asipto/li...", 2, Array(12) ) @ /var/www/html/siremis/openbiz/bin/sysheader.inc 117
function: userErrorHandler ( 2, "require_once(XML/RPC.php): failed to open stream: No such file o...", "/var/www/html/siremis/siremis/modules/sipadmin/service/asipto/li...", 2, Array(12) ) @ /var/www/html/siremis/siremis/modules/sipadmin/service/asipto/libs/cmds/serxr.php 2
function: require_once ( ) @ /var/www/html/siremis/siremis/modules/sipadmin/service/asipto/libs/cmds/serxr.php 2
function: include_once ( "/var/www/html/siremis/siremis/modules/sipadmin/service/asipto/li..." ) @ /var/www/html/siremis/siremis/modules/sipadmin/cms/form/XrcmdsForm.php 2
function: include_once ( "/var/www/html/siremis/siremis/modules/sipadmin/cms/form/XrcmdsFo..." ) @ /var/www/html/siremis/openbiz/bin/ObjectFactory.php 162
function: constructObject ( "sipadmin.cms.form.XrcmdsForm" ) @ /var/www/html/siremis/openbiz/bin/ObjectFactory.php 56
function: getObject ( "sipadmin.cms.form.XrcmdsForm" ) @ /var/www/html/siremis/openbiz/bin/easy/EasyView.php 348
function: initAllForms ( ) @ /var/www/html/siremis/openbiz/bin/easy/EasyView.php 232
function: render ( ) @ /var/www/html/siremis/openbiz/bin/BizController.php 221
function: renderView ( "sipadmin.view.XrcmdsView", "", "", Null, "" ) @ /var/www/html/siremis/openbiz/bin/BizController.php 107
function: dispatchRequest ( ) @ /var/www/html/siremis/openbiz/bin/BizController.php 32
function: include_once ( "/var/www/html/siremis/openbiz/bin/BizController.php" ) @ /var/www/html/siremis/siremis/bin/controller.php 6
function: include ( "/var/www/html/siremis/siremis/bin/controller.php" ) @ /var/www/html/siremis/siremis/bin/_forward.php 102
function: include ( "/var/www/html/siremis/siremis/bin/_forward.php" ) @ /var/www/html/siremis/siremis/index.php 3

**Comment by miconda** [comment]
See the installation guidelines about components:

  * https://kb.asipto.com/siremis:install51x:main#install_additional_components

**Comment by xevilstar** [comment]
> See the installation guidelines about components:
> 
>     * https://kb.asipto.com/siremis:install51x:main#install_additional_components

404
