### ISSUE TITLE
/siremis/system/general_default    -> not found

### ISSUE THREAD

**Issue by hansju** [asipto/siremis-php#51]
fresh installation on:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
apache:  2.4.29-1ubuntu4.11
php Version: 1:  7.2+60ubuntu1

and siremis with git clone from this place.

**Comment by miconda** [comment]
You need to enable mod rewrite for apache. See the guidelines at:

  * http://kb.asipto.com/siremis:install51x:main

If not working, reopen and provide detailed steps that you did for installation.

**Comment by hansju** [comment]
Perfekt, solutions works well.
