### ISSUE TITLE
php 7.4 support

### ISSUE THREAD

**Issue by yeya** [asipto/siremis-php#56]
When trying to login the first time after clean install
`[{"target":"ERROR","content":"
\n[2020-05-04 07:16:18 (GMT)] An exception occurred while executing this script:
\nError message: #8192, Function get_magic_quotes_gpc() is deprecated<\/font>
\nScript name and line number of error: \/var\/www\/siremis\/openbiz\/bin\/ClientProxy.php:190<\/font>
\n

function:<\/b> errorHandler ( 8192, \"Function get_magic_quotes_gpc() is deprecated\", \"\/var\/www\/siremis\/openbiz\/bin\/ClientProxy.php\", 190, Array(3) ) @ \/var\/www\/siremis\/openbiz\/bin\/sysheader.inc 117\n
function:<\/b> userErrorHandler ( 8192, \"Function get_magic_quotes_gpc() is deprecated\", \"\/var\/www\/siremis\/openbiz\/bin\/ClientProxy.php\", 190, Array(3) ) @ \/var\/www\/siremis\/openbiz\/bin\/ClientProxy.php 190\n
function:<\/b> getFormInputs ( \"username\" ) @ \/var\/www\/siremis\/openbiz\/bin\/easy\/EasyForm.php 1401\n
function:<\/b> readInputRecord ( ) @ \/var\/www\/siremis\/siremis\/modules\/user\/form\/LoginForm.php 73\n
function:<\/b> Login ( ) @ \/var\/www\/siremis\/openbiz\/bin\/BizController.php 310\n
function:<\/b> invoke ( ) @ \/var\/www\/siremis\/openbiz\/bin\/BizController.php 110\n
function:<\/b> dispatchRequest ( ) @ \/var\/www\/siremis\/openbiz\/bin\/BizController.php 32\n
function:<\/b> include_once ( \"\/var\/www\/siremis\/openbiz\/bin\/BizController.php\" ) @ \/var\/www\/siremis\/siremis\/bin\/controller.php 6<\/div>\n`

**Comment by miconda** [comment]
Should be fixed now in master branch. Thanks.
