### ISSUE TITLE
Cannot connect to postgres database

### ISSUE THREAD

**Issue by yok0** [asipto/siremis-php#59]
Despite me being slightly reluctant to PHP, I decided to give Siremis a try.
I used my existing postgres database and there seem to be some kind of issue there.
During the setup after I enter all the details I get:`ERROR: SQLSTATE[08006] [7] FATAL: database "siremis" does not exist` If I create the db it complains there's duplicate. 
Either way I cannot move forward. I could but no tables would be created and I would not be able to log in.
Any solution to this ?
![image](https://user-images.githubusercontent.com/6692754/84555936-7959c200-ad17-11ea-9e2b-8125a71b4841.png)

**Comment by miconda** [comment]
Postgres is actually not supported, see:

  - https://github.com/asipto/siremis/issues/8

Try with mysql and if you get issues, then reopen, adding the details for that case.
