### ISSUE TITLE
Report vulnerability

### ISSUE THREAD

**Issue by enferas** [asipto/siremis-php#60]
Hello,

I would like to report for a vulnerability.

Can I report it here or you prefer if I send it by email ?

**Comment by miconda** [comment]
Hello,

thanks, send it via email to miconda@gmail.com .

As an overall advise, siremis is designed as an admin tool, not audited for security and it has to be run on a protected environment (e.g., private network, firewall allowing only trusted peers). A similar note is in its docs:

  * https://kb.asipto.com/siremis:install53x:main#security_considerations
  * https://kb.asipto.com/siremis:install53x:public-registration

**Comment by miconda** [comment]
Have you sent me any email? I haven't noticed any so far.
