### ISSUE TITLE
Add automatic reload SECFILTER

### ISSUE THREAD

**Issue by voztovoice** [asipto/siremis-php#61]
Hello,
would be a great enhancement automatize reload data of SECFILTER module. 
Now when you add a new entry on SECFILTER from Siremis you have to execute **kamcmd secfilter.reload** from Linux terminal to recharge data from database to kamailio memory.
Thank you
Regards

**Comment by miconda** [comment]
There is an rpc panel that you can configure and run commands directly from siremis:

  * https://kb.asipto.com/siremis:install53x:jsonrpc-commands

If you want to implement a button on the secfilter page, PR is welcome! There should be couple of other pages doing it (maybe dispatcher ?!?).
