### ISSUE TITLE
How to change language in siremis web interface?

### ISSUE THREAD

**Issue by Mohammadb06** [asipto/siremis-php#62]
Hello everyone
I’m new in siremis as web interface of kamailio and I immediately need your help,I installed kamailio and siremis and login in siremis web interface,I can work with it but now I have a problem.
I want to change menu language there is an option in(setting->translate->manage languages) add my desired language and click save and i see this error:
Error message: #2, count(): Parameter must be an array or an object that implements Countable
Script name and line number of error: [/var/www/siremis-5.3.x/siremis/modules/translation/lib/LangPackCreator.php
![pro](https://user-images.githubusercontent.com/84019067/146781463-cb995a12-c510-40a6-9174-9ad7e60aa969.png)

what’s wrong and what should I do to resolve it?
thank you for your help and I am pleased to receive your response

**Comment by miconda** [comment]
The multi-language feature is not implemented for siremis, it is part of the framework that was used to build siremis, but not available in siremis. You have to ignore it or implement it yourself.
