### ISSUE TITLE
can't open cmp file to write

### ISSUE THREAD

**Issue by ahmednamoha** [asipto/siremis-php#63]
[php7:warn] [pid 8898] [client xx.xx.xx.xx:xxxx4] PHP Warning:  mkdir(): No such file or directory in /var/www/siremis/openbiz/bin/Resource.php on line 405
[Tue Feb 01 06:43:27.558774 2022] [php7:warn] [pid 8898] [client xx.xx.xx.xx:xxxx] PHP Warning:  fopen(/var/www/siremis/siremis/files/cache/metadata/BF2DE9ED_logService.cmp): failed to open stream: No such file or directory in /var/www/siremis/openbiz/bin/Resource.php on line 406

**Comment by miconda** [comment]
It seems you haven't run all the commands from the installation guidelines:

  * https://kb.asipto.com/siremis:install53x:main

Look also at the docker file, might be useful to check the commands run there:

  * https://github.com/asipto/siremis/blob/master/misc/docker/Dockerfile.debian10-gitdev

**Comment by miconda** [comment]
Closing.
