### ISSUE TITLE
Compatibility with PHP 5.6

### ISSUE THREAD

**Issue by reidforrest1** [asipto/siremis-php#7]
Newly Installed on Ubuntu 15.04 and PHP 5.6.4-4. After running the install wizard and trying to log in as admin I get an error popup. I have seen this posted by others to various forums as well.

```
[{"target":"ERROR","content":"
\n[2015-09-17 23:42:07 (GMT)] An exception occurred while executing this script:
\nError message: #8192, Non-static method BizSystem::getConfiguration() should not be called statically, assuming $this from incompatible context<\/font>
\nScript name and line number of error: \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php:268<\/font>
\n

function:<\/b> errorHandler ( 8192, \"Non-static method BizSystem::getConfiguration() should not be ca...\", \"\/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php\", 268, Array(0) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/sysheader.inc 117\n
function:<\/b> userErrorHandler ( 8192, \"Non-static method BizSystem::getConfiguration() should not be ca...\", \"\/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php\", 268, Array(0) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php 268\n
function:<\/b> setQuoteIdentifiers ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php 177\n
function:<\/b> __construct ( Array(1) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj.php 37\n
function:<\/b> __construct ( Array(1) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/ObjectFactory.php 166\n
function:<\/b> constructObject ( \"system.do.UserDO\" ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/ObjectFactory.php 56\n
function:<\/b> getObject ( \"system.do.UserDO\", 0 ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizSystem.php 252\n
function:<\/b> getObject ( \"system.do.UserDO\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/modules\/service\/authService.php 92\n
function:<\/b> authDBUser ( \"admin\", \"admin\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/modules\/service\/authService.php 66\n
function:<\/b> authenticateUser ( \"admin\", \"admin\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/modules\/user\/form\/LoginForm.php 92\n
function:<\/b> Login ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php 310\n
function:<\/b> invoke ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php 110\n
function:<\/b> dispatchRequest ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php 32\n
function:<\/b> include_once ( \"\/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/bin\/controller.php 6<\/div>\n
Please ask system administrator for help...<\/div>\n"}]
```

**Comment by miconda** [comment]
Are you using the last version from git or the tarball of the last release? Recently there were some commits that should solve this issue.

**Comment by reidforrest1** [comment]
I have tried both with the same result.

**Comment by miconda** [comment]
It doesn't seem you run last git master branch, becasue the line has another content, it is no BizSystem::getConfiguration() there, see:

https://github.com/asipto/siremis/blob/master/openbiz/bin/data/BizDataObj_Abstract.php#L268

Make a clean clone of the git master.

**Comment by reidfo** [comment]
Hello!

 

New message, please read <http://lezhapi.com/seemed.php?zwb>

 

Reid Forrest

**Comment by sousdubois** [comment]
Hi,

I have the same issue.
What i use is 
Operation System    Linux Debian 8.3
PHP version     5.6.17-0+deb8u1  
Openbiz Path    /var/www/siremis-4.2.0/openbiz  
Zend Framework Path     /var/www/siremis-4.2.0/openbiz/others/  
Zend Framework  1.9.7

This is the manual i used : http://kb.asipto.com/siremis:install42x:main

The error i get is 

[{"target":"ERROR","content":"
\n[2016-03-02 10:17:43 (GMT)] An exception occurred while executing this script:
\nError message: #8192, Non-static method BizSystem::getConfiguration() should not be called statically, assuming $this from incompatible context<\/font>
\nScript name and line number of error: \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php:268<\/font>
\n

function:<\/b> errorHandler ( 8192, \"Non-static method BizSystem::getConfiguration() should not be ca...\", \"\/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php\", 268, Array(0) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/sysheader.inc 117\n
function:<\/b> userErrorHandler ( 8192, \"Non-static method BizSystem::getConfiguration() should not be ca...\", \"\/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php\", 268, Array(0) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php 268\n
function:<\/b> setQuoteIdentifiers ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj_Abstract.php 177\n
function:<\/b> __construct ( Array(1) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/data\/BizDataObj.php 37\n
function:<\/b> __construct ( Array(1) ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/ObjectFactory.php 166\n
function:<\/b> constructObject ( \"system.do.UserDO\" ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/ObjectFactory.php 56\n
function:<\/b> getObject ( \"system.do.UserDO\", 0 ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizSystem.php 252\n
function:<\/b> getObject ( \"system.do.UserDO\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/modules\/service\/authService.php 92\n
function:<\/b> authDBUser ( \"admin\", \"admin\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/modules\/service\/authService.php 66\n
function:<\/b> authenticateUser ( \"admin\", \"admin\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/modules\/user\/form\/LoginForm.php 92\n
function:<\/b> Login ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php 310\n
function:<\/b> invoke ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php 110\n
function:<\/b> dispatchRequest ( ) @ \/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php 32\n
function:<\/b> include_once ( \"\/var\/www\/siremis-4.2.0\/openbiz\/bin\/BizController.php\" ) @ \/var\/www\/siremis-4.2.0\/siremis\/bin\/controller.php 6<\/div>\nPlease ask system administrator for help...<\/div>\n"}]

Please help.

Best Regards

Sous

**Comment by reidfo** [comment]
Hello!

 

You have a new message, please read <http://Ycoffee.vn/terrorist.php?l36>

 

Recipients

**Comment by reidfo** [comment]
Hi,
I know it might be something strange, but still so interesting, you have to see it here <http://stareslithi.thyroidrage.info/aefedpc>

Regards, Recipients

**Comment by reidfo** [comment]
Hi,

My dear friend I've got such a good news for you, just take a look at <http://shantultehe.galachy.com/aeuqdr>

All best, Reid Forrest
