### ISSUE TITLE
Call to a member function getQuoted() on array

### ISSUE THREAD

**Issue by Mancy** [asipto/siremis-php#9]
PHP Fatal error:  Call to a member function getQuoted() on array in /var/www/siremis-4.2.0/openbiz/bin/data/BizDataSql.php on line 237, referer: http://yourdomain.com/siremis/system/user_detail/1

**Comment by miconda** [comment]
Fixed in latest master.

**Comment by imcdona** [comment]
The download available at http://siremis.asipto.com/pub/downloads/siremis/siremis-4.3.0.tgz still has the old code and needs to be updated.

I can confirm that the issue is resolved after using the latest master from github.
